version: '3.7'

services:

  postgres:
    image: postgis/postgis
    ports: 
      - '5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres

volumes:
  postgres-data: {}
